# The URL the site will be built for
base_url = "https://hydroakri.github.io/"
title = "Hydroakri's Blog"
description = "与太阳共燃的内在性"

# Enable the theme
theme = "Linkita"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "OneHalfDark"

[search]
index_format = "elasticlunr_json"

[extra]
# Put all your custom variables here
author = "Hydroakri"

# Enable KaTeX math formula support globally
math = false

# Enable Mermaid support globally
mermaid = false

# Enable comments globally
comment = false

# Title separator
title_separator = " | "

# The top menu
header_menu_name = "main"

# Menu configuration
[extra.menus]
main = [
  { url = "/", name = "Home" },
  { url = "/tags", name = "Tags" },
  { url = "/archives", name = "Archives" },
  { url = "/about", name = "About" },
]

# Social icons
[extra.social]
github = { name = "GitHub", url = "https://github.com/hydroakri" }
lastfm = { name = "Last.fm", url = "https://www.last.fm/user/hydroakri" }
steam = { name = "Steam", url = "https://steamcommunity.com/id/hydroakri" }
qq = { name = "QQ", url = "https://qm.qq.com/cgi-bin/qm/qr?k=lOkoiWANVJYuKaArCStQTFjjzfxpmc9V&noverify=0&personal_qrcode_source=3" }
twitter = { name = "Twitter", url = "https://twitter.com/ihbswsy" }
mastodon = { name = "Mastodon", url = "https://m.cmx.im/@hydroakri" }
bilibili = { name = "Bilibili", url = "https://space.bilibili.com/4912217" }

# Profile mode
[extra.profiles.hydroakri]
avatar_url = "https://img2.doubanio.com/icon/ul265151065.jpg"
avatar_alt = "Hydroakri's avatar"
name = "Hydroakri"
bio = "与太阳共燃的内在性"
social = [
    { name = "github", url = "https://github.com/hydroakri" },
    { name = "mastodon", url = "https://m.cmx.im/@hydroakri" },
    { name = "twitter", url = "https://twitter.com/ihbswsy" },
    { name = "bilibili", url = "https://space.bilibili.com/4912217" },
    { name = "steam", url = "https://steamcommunity.com/id/hydroakri" },
]

# Pagination
paginate_by = 5

# Page info
page_info = ["date", "word_count", "reading_time", "taxonomies"]

# Page info on paginator
page_info_on_paginator = ["date"]